version: "3"
services:
  rundeck:
    build:
      context: .
      args:
        RUNDECK_IMAGE: ${RUNDECK_IMAGE:-rundeckpro/enterprise:SNAPSHOT}
    container_name: rundeck-ssl
    command: "-Dserver.https.port=4443 -Drundeck.ssl.config=/home/rundeck/server/config/ssl.properties"
    ports:
    - 4443:4443
    environment:
      RUNDECK_GRAILS_URL: https://rundeck:4443